import 'reflect-metadata';
import { NestFactory } from '@nestjs/core';
import { readFile, writeFile } from 'node:fs/promises';
import { stringify } from 'yaml';
import { AppModule } from './app.module.js';
import { API_PREFIX, createApiDocument } from './swagger.js';

// Create the same route/schema document as the server, without listening on a port.
const app = await NestFactory.create(AppModule, { logger: false });
try {
  app.setGlobalPrefix(API_PREFIX);
  const output = new URL('../../swagger.yaml', import.meta.url);
  const yaml =
    '# Generated by npm run swagger:generate. Edit NestJS DTOs/controllers, then regenerate.\n' +
    stringify(createApiDocument(app), { aliasDuplicateObjects: false });
  if (process.argv.includes('--check')) {
    const saved = await readFile(output, 'utf8');
    if (saved !== yaml)
      throw new Error(
        'swagger.yaml is stale. Run npm run swagger:generate and commit the updated file.',
      );
    console.log('swagger.yaml matches the current API metadata.');
  } else {
    await writeFile(output, yaml, 'utf8');
    console.log('Generated swagger.yaml at the repository root.');
  }
} finally {
  await app.close();
}
